Controllers/MarcasVehiculosController.cs
using GuanajuatoAdminUsuarios.Entity;
using GuanajuatoAdminUsuarios.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Example.WebUI.Controllers
{
    public class MarcasVehiculosController : Controller
    {
        DBContextInssoft dbContext = new DBContextInssoft();
        public IActionResult Index()
        {
            //var products = dbContext.Products.ToList();
            var ListMarcasModel = GetMarcas();

            return View(ListMarcasModel);

        }


        #region Modal Action
        public ActionResult IndexModal()
        {
            var ListMarcasModel = GetMarcas();
            //return View("IndexModal");
            return View("Index", ListMarcasModel);
        }

        [HttpPost]
        public ActionResult AgregarPacial()
        {
            //SetDDLDependencias();
            return PartialView("_Crear");
        }

        [HttpPost]
        public ActionResult EditarParcial(int IdMarcaVehiculo)
        {
            var marcasVehiculosModel = GetMarcaByID(IdMarcaVehiculo);
            return View("_Editar", marcasVehiculosModel);
        }
        [HttpPost]
        public ActionResult EliminarMarcaParcial(int IdMarcaVehiculo)
        {
            var marcasVehiculosModel = GetMarcaByID(IdMarcaVehiculo);
            return View("_Eliminar", marcasVehiculosModel);
        }

        [HttpPost]
        public IActionResult GetUpdate(int IdMarcaVehiculo)
        {
            var marcaVehiculoModel = GetMarcaByID(IdMarcaVehiculo);
            return View(marcaVehiculoModel);
        }


        public JsonResult Categories_Read()
        {
            var result = new SelectList(dbContext.MarcasVehiculos.ToList(), "IdMarcaVehiculo", "MarcaVehiculo");
            return Json(result);
        }



        [HttpPost]
        public ActionResult CreatePartialModal(MarcaVehiculoModel model)
        {
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("MarcaVehiculo");
            if (ModelState.IsValid)
            {
                //Crear el producto

                CreateMarca(model);
                var ListMarcasModel = GetMarcas();
                return PartialView("_ListaMarcasVehiculos", ListMarcasModel);
            }
            //SetDDLCategories();
            //return View("Create");
            return PartialView("_Crear");
        }

        public ActionResult UpdatePartialModal(MarcaVehiculoModel model)
        {
            bool switchMarcas = Request.Form["MarcasSwitch"].Contains("true");
            model.Estatus = switchMarcas ? 1 : 0;
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("MarcaVehiculo");
            if (ModelState.IsValid)
            {
                //Crear el producto

                UpdateMarca(model);
                var ListMarcasModel = GetMarcas();
                return PartialView("_ListaMarcasVehiculos", ListMarcasModel);
            }
            //SetDDLCategories();
            //return View("Create");
            return PartialView("_Editar");
        }

        public ActionResult EliminarMarcaModal(MarcaVehiculoModel model)
        {
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("MarcaVehiculo");
            if (ModelState.IsValid)
            {

                DeleteMarca(model);
                var ListMarcasModel = GetMarcas();
                return PartialView("_ListaMarcasVehiculos", ListMarcasModel);
            }
            //SetDDLCategories();
            //return View("Create");
            return PartialView("_Eliminar");
        }



        public JsonResult GetMarca2([DataSourceRequest] DataSourceRequest request)
        {
            var ListMarcasModel = GetMarcas();

            return Json(ListMarcasModel.ToDataSourceResult(request));
        }




        #endregion


        #region Acciones a base de datos

        public void CreateMarca(MarcaVehiculoModel model)
        {
            MarcasVehiculo marca = new MarcasVehiculo();
            marca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            marca.MarcaVehiculo = model.MarcaVehiculo;
            marca.Estatus = 1;
            marca.FechaActualizacion = DateTime.Now;
            dbContext.MarcasVehiculos.Add(marca);
            dbContext.SaveChanges();
        }

        public void UpdateMarca(MarcaVehiculoModel model)
        {
            MarcasVehiculo marca = new MarcasVehiculo();
            marca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            marca.MarcaVehiculo = model.MarcaVehiculo;
            marca.Estatus = model.Estatus;
            marca.FechaActualizacion = DateTime.Now;
            dbContext.Entry(marca).State = EntityState.Modified;
            dbContext.SaveChanges();

        }

        public void DeleteMarca(MarcaVehiculoModel model)
        {
            //Sera mas rapido con automapeo de clases
            MarcasVehiculo marca = new MarcasVehiculo();
            marca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            marca.MarcaVehiculo = model.MarcaVehiculo;
            marca.Estatus = 0;
            marca.FechaActualizacion = DateTime.Now;
            dbContext.Entry(marca).State = EntityState.Modified;
            dbContext.SaveChanges();

        }

        private void SetDDLMarcas()
        {
            ///Espacio en memoria de manera temporal que solo existe en la petición bool, list, string ,clases , selectlist
            ViewBag.Categories = new SelectList(dbContext.MarcasVehiculos.ToList(), "IdMarcaVehiculo", "MarcaVehiculo");
        }


        public MarcaVehiculoModel GetMarcaByID(int IdMarcaVehiculo)
        {

            var productEnitity = dbContext.Dependencias.Find(IdMarcaVehiculo);

            var marcaModel = (from marcasVehiculos in dbContext.MarcasVehiculos.ToList()
                              select new MarcaVehiculoModel

                              {
                                  IdMarcaVehiculo = marcasVehiculos.IdMarcaVehiculo,
                                  MarcaVehiculo = marcasVehiculos.MarcaVehiculo,


                              }).Where(w => w.IdMarcaVehiculo == IdMarcaVehiculo).FirstOrDefault();

            return marcaModel;
        }

        /// <summary>
        /// Linq es una tecnologia de control de datos (excel, txt,EF,sqlclient etc)
        /// para la gestion un mejor control de la info
        /// </summary>
        /// <returns></returns>
        public List<MarcaVehiculoModel> GetMarcas()
        {
            var ListMarcasModel = (from marcasVehiculos in dbContext.MarcasVehiculos.ToList()
                                   join estatus in dbContext.Estatus.ToList()
                                    on marcasVehiculos.Estatus equals estatus.estatus
                                   where marcasVehiculos.Estatus == 1

                                   select new MarcaVehiculoModel
                                   {
                                       IdMarcaVehiculo = marcasVehiculos.IdMarcaVehiculo,
                                       MarcaVehiculo = marcasVehiculos.MarcaVehiculo,
                                       Estatus = marcasVehiculos.Estatus,
                                       estatusDesc = estatus.estatusDesc

                                   }).ToList();
            return ListMarcasModel;
        }
        #endregion



    }
}

Views/MarcasVehiculos/Create.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel
@{
}


<div class="row">
    <div class="col-md-10">
        <h2>Crear Marca</h2>
    </div>
    <br />
   
</div>
<hr />
<br />

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Create", "MarcasVehiculos"))
        {
            @(Html.Kendo().TextBoxFor(t => t.MarcaVehiculo)
                .HtmlAttributes(new { placeholder = "Marca", required = "required", validationmessage = "Enter Category Name" })
                .Label(l => l.Content("Marca de Vehiculo"))
                )
            <br />  <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href='@Url.Action("Index")' class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </div>

        }

    </div>
</div>

Views/MarcasVehiculos/Delete.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel
@{
}


<div class="row">
    <div class="col-md-10">
        <h2>Eliminar Categoria</h2>
    </div>
    <br />
    <div class="col-md-2">
        @Html.ActionLink("Cancelar","Index",null,new{@class="btn btn-info"})
    </div>
</div>
<hr />
<br />

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Delete", "MarcasVehiculos"))
        {
            @Html.HiddenFor(m=>m.IdMarcaVehiculo)
            ;

            @(Html.Kendo().TextBoxFor(t => t.MarcaVehiculo)
                .HtmlAttributes(new
                {
                    placeholder = "Marca de Vehiculo",
                    required = "required",
                    validationmessage = "Enter Category Name",
                    @readonly = "readonly"
                })
                .Label(l => l.Content("Marca de Vehiculo"))
                )
            <br />  <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href='@Url.Action("Index")' class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </div>

        }

    </div>
</div>

Views/MarcasVehiculos/Index.cshtml
@model List<GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel>
@*RazorCoder*@
<div class="mainContainer bg-light">
        <section class="mx-md-3 mx-lg-4 mx-xl-5 bg-white boxShadow my-5 rounded">
            <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                <div class="col-12 col-md-6 col-lg-5 col-xl-auto">
                    <div class="row align-items-center justify-content-center justify-content-md-start">
                        <div class="col-auto">
                            <i class="icon-marca h1 colorPrimary"></i>
                        </div>
                        <div class="col-auto my-3">
                            <h2 class="m-0 h3"><b>Catalogo de vehiculos</b></h2>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-7 col-xl-auto">
                    <div class="row">
                        <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                            <button href ="#" id="btnNuevaMarca" onclick="mostrarModal()">
                                <h6 class="m-0 d-flex align-items-center"><i class="icon-addMarca h5 mb-0 me-2"></i><b>Agregar nueva marca</b></h6>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="bg-light py-1"></div>
                </div>
            </div>
            <div class="row justify-content-between mb-1 titleCustom">
                <div class="col-12 col-md-auto mt-4 mb-2">
                    <h5 class="px-4"><b>Listado de marcas de vehículos</b></h5>
                    <h6 class="px-4 text-muted">Edita o elimina las marcas de vehículos.</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-12 mb-4 px-4 rounded gridCustom">
            <div id="tablaMarcas">
                <partial name="_ListaMarcasVehiculos" model="Model" />
        
    <div class="modal fade modalCustom" id="addMarca" tabindex="-1" aria-labelledby="addMarcaLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body" id="ModalBodyCreate">
                </div>
            </div>

        </div>
    </div>

<!--UPDATE MODAL-->

<div class="modal fade modalCustom" id="editarMarca" tabindex="-1" aria-labelledby="editMarcaLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">

        <!-- Modal content-->
        <div class="modal-content">
        
            <div class="modal-body" id="ModalBodyUpdate">
            </div>
        </div>

    </div>
</div>

<!--/////////////////////////////////////////////////////////////////////****ELIMINAR****/////////////////////////////////////////////////////////////////////////-->
<div class="modal fade modalCustom" id="eliminarMarca" tabindex="-1" aria-labelledby="editMarcaLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body" id="ModalBodyEliminarMarca">

            </div>
        </div>

    </div>
</div>

</div>
</div>
</div>
</section>
</div>

<script>
    function mostrarModal() {
        $.ajax({
            url: '@Url.Action("AgregarPacial")',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                $('#ModalBodyCreate').html(data);
                $('#addMarca').modal('show');
            }
        });
    }





</script>

Views/MarcasVehiculos/IndexModal.cshtml
@model List<GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel>
@*RazorCoder*@
<div class="mainContainer bg-light">
        <section class="mx-md-3 mx-lg-4 mx-xl-5 bg-white boxShadow my-5 rounded">
            <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                <div class="col-12 col-md-6 col-lg-5 col-xl-auto">
                    <div class="row align-items-center justify-content-center justify-content-md-start">
                        <div class="col-auto">
                            <i class="icon-marca h1 colorPrimary"></i>
                        </div>
                        <div class="col-auto my-3">
                            <h2 class="m-0 h3"><b>Catalogo de vehiculos</b></h2>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-7 col-xl-auto">
                    <div class="row">
                        <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                            <button href ="#" id="btnNuevaMarca" onclick="mostrarModal()">
                                <h6 class="m-0 d-flex align-items-center"><i class="icon-addMarca h5 mb-0 me-2"></i><b>Agregar nueva marca</b></h6>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="bg-light py-1"></div>
                </div>
            </div>
            <div class="row justify-content-between mb-1 titleCustom">
                <div class="col-12 col-md-auto mt-4 mb-2">
                    <h5 class="px-4"><b>Listado de marcas de vehículos</b></h5>
                    <h6 class="px-4 text-muted">Edita o elimina las marcas de vehículos.</h6>
                </div>
            </div>
            <div class="row">
                <div class="col-12 mb-4 px-4 rounded gridCustom">
            <div id="tablaMarcas">
                <partial name="_ListaMarcasVehiculos" model="Model" />
        
    <div class="modal fade modalCustom" id="addMarca" tabindex="-1" aria-labelledby="addMarcaLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-body" id="ModalBodyCreate">
                </div>
            </div>

        </div>
    </div>

<!--UPDATE MODAL-->

<div class="modal fade modalCustom" id="editarMarca" tabindex="-1" aria-labelledby="editMarcaLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">

        <!-- Modal content-->
        <div class="modal-content">
        
            <div class="modal-body" id="ModalBodyUpdate">
            </div>
        </div>

    </div>
</div>

<!--/////////////////////////////////////////////////////////////////////****ELIMINAR****/////////////////////////////////////////////////////////////////////////-->
<div class="modal fade modalCustom" id="eliminarMarca" tabindex="-1" aria-labelledby="editMarcaLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body" id="ModalBodyEliminarMarca">

            </div>
        </div>

    </div>
</div>

</div>
</div>
</div>
</section>
</div>

<script>
    function mostrarModal() {
        $.ajax({
            url: '@Url.Action("AgregarPacial")',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                $('#ModalBodyCreate').html(data);
                $('#addMarca').modal('show');
            }
        });
    }





</script>

Views/MarcasVehiculos/Update.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel
@{
}


<div class="row">
    <div class="col-md-10">
        <h2>Modificar Marca</h2>
    </div>
    <br />
    <div class="col-md-2">
        @Html.ActionLink("Cancelar","Index",null,new{@class="btn btn-info"})
    </div>
</div>
<hr />
<br />

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Update", "MarcasVehiculos"))
        {
            @Html.HiddenFor(m=>m.IdMarcaVehiculo);
            

            @(Html.Kendo().TextBoxFor(t => t.MarcaVehiculo)
                .HtmlAttributes(new { placeholder = "Marca de Vehiculo", required = "required", validationmessage = "Introducemarca de vehiculo" })
                .Label(l => l.Content("Marca de Vehiculo"))
                )
            <br />  <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href='@Url.Action("Index")' class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </div>

        }

    </div>
</div>

Views/MarcasVehiculos/_Crear.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel


            <section class=" bg-white rounded">
                <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                    <div class="col-auto pe-0">
                        <div class="row align-items-center justify-content-center justify-content-md-start">
                            <div class="col-auto pe-0">
                                <i id="addMarca"class="icon-addMarca h1 colorPrimary"></i>
                            </div>
                            <div class="col-auto my-3">
                                <h2 class="m-0 h3"><b>Agregar marca de vehículo</b></h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div class="row">
                            <div class="col-auto my-3">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light py-1"></div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12 my-4">
                        <h5 class="px-4"><b>Datos de carretera</b></h5>
                        <h6 class="px-4 text-muted">Completa los datos obligatorios para guardar.</h6>
                    </div>
                </div>
                <form id="ProductForm" class="row px-4 mb-4 align-items-end justify-content-center">
                        <div class="col-12 col-md-6">
                        <div class="controlForm my-3">
                            @(Html.Kendo().TextBoxFor(t=>t.MarcaVehiculo)
                                .Label(l => l.Content("Marca de vehículo <b>(obligatorio)</b>:"))
                                .Placeholder("Ingresa una nueva marca de vehículo")
                                .HtmlAttributes(new { style = "width: 100%" })
                                )

                        </div>
                    </div>

                </form>
                <div class="row my-4">
                    <div class="col-12 col-md-6 mx-md-auto">
                        <div class="row justify-content-around">
                            <div class="col-auto btnOutline my-2 mx-auto mx-xl-2 p-0">
                                <button type="button" data-bs-dismiss="modal" aria-label="Close">
                                    <h6 class="m-0 px-3"><b>Cerrar</b></h6>
                                </button>
                            </div>
                            <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                         <button class="btnPrimary px-3" onclick="submitProduct()">
                            <h5 class="m-0"><b>Guardar</b></h5>
                        </button>                           
                            </div>
                        </div>
                    </div>


                </div>
            </section>
    
<script>
    function submitProduct() {

        var Mydata = $("#ProductForm").serialize();
        console.log(Mydata);
        $('#addMarca').modal('hide');
        $('body').removeClass('model-open');
        $('.modal-backdrop').remove();
        $.ajax({
            url: '@Url.Action("CreatePartialModal")',
            type: 'POST',
            data: Mydata,
            success: function (result) {
                $("#tablaDependencias").html(result);
            }
        });
    }

</script>

Views/MarcasVehiculos/_Create.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel


            <section class=" bg-white rounded">
                <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                    <div class="col-auto pe-0">
                        <div class="row align-items-center justify-content-center justify-content-md-start">
                            <div class="col-auto pe-0">
                                <i id="addMarca"class="icon-addMarca h1 colorPrimary"></i>
                            </div>
                            <div class="col-auto my-3">
                                <h2 class="m-0 h3"><b>Agregar marca de vehículo</b></h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div class="row">
                            <div class="col-auto my-3">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light py-1"></div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12 my-4">
                        <h5 class="px-4"><b>Datos de carretera</b></h5>
                        <h6 class="px-4 text-muted">Completa los datos obligatorios para guardar.</h6>
                    </div>
                </div>
                <form id="ProductForm" class="row px-4 mb-4 align-items-end justify-content-center">
                        <div class="col-12 col-md-6">
                        <div class="controlForm my-3">
                            @(Html.Kendo().TextBoxFor(t=>t.MarcaVehiculo)
                                .Label(l => l.Content("Marca de vehículo <b>(obligatorio)</b>:"))
                                .Placeholder("Ingresa una nueva marca de vehículo")
                                .HtmlAttributes(new { style = "width: 100%" })
                                )

                        </div>
                    </div>

                </form>
                <div class="row my-4">
                    <div class="col-12 col-md-6 mx-md-auto">
                        <div class="row justify-content-around">
                            <div class="col-auto btnOutline my-2 mx-auto mx-xl-2 p-0">
                                <button type="button" data-bs-dismiss="modal" aria-label="Close">
                                    <h6 class="m-0 px-3"><b>Cerrar</b></h6>
                                </button>
                            </div>
                            <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                         <button class="btnPrimary px-3" onclick="submitProduct()">
                            <h5 class="m-0"><b>Guardar</b></h5>
                        </button>                           
                            </div>
                        </div>
                    </div>


                </div>
            </section>
    
<script>
    function submitProduct() {

        var Mydata = $("#ProductForm").serialize();
        console.log(Mydata);
        $('#addMarca').modal('hide');
        $('body').removeClass('model-open');
        $('.modal-backdrop').remove();
        $.ajax({
            url: '@Url.Action("CreatePartialModal")',
            type: 'POST',
            data: Mydata,
            success: function (result) {
                $("#tablaDependencias").html(result);
            }
        });
    }

</script>

Views/MarcasVehiculos/_Editar.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel

<section class=" bg-white rounded">
    <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
        <div class="col-auto pe-0">
            <div class="row align-items-center justify-content-center justify-content-md-start">
                <div class="col-auto pe-0">
                    <i class="icon-deleteMarca h1 colorDanger"></i>
                </div>
                <div class="col-auto my-3">
                    <h2 class="m-0 h3"><b>Editar marca de vehículo</b></h2>
                </div>
            </div>
        </div>
        <div class="col-auto">
            <div class="row">
                <div class="col-auto my-3">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="bg-light py-1"></div>
        </div>

    </div>
     <div class="row">
        <div class="col-12 my-4">
            <h5 class="px-4"><b>Datos del oficial de tránsito</b></h5>
            <h6 class="px-4 text-muted">Completa los datos obligatorios para guardar.</h6>
        </div>
    </div>
    <form id="EditarMarcaForm" class="px-4 mb-4">
        <div class="col-12 col-lg-6 my-4">
            @(Html.Kendo().SwitchFor(t => t.ValorEstatusMarcas)
                .Name("MarcasSwitch")
                .Checked(true)
                .Messages(c => c.Checked("Activo").Unchecked("Inactivo"))
                .HtmlAttributes(new { data_valor = 1 })

                )
        </div>
        <div class="col-12 col-md-6">
            <div class="controlForm my-3">
                @Html.HiddenFor(m=>m.IdMarcaVehiculo)
                @(Html.Kendo().TextBoxFor(t => t.MarcaVehiculo)
                    .Label(l => l.Content("Nombre <b>(obligatorio)</b>:"))
                    .Placeholder("Ingresa un nueva color")
                    .HtmlAttributes(new { style = "width: 100%" })
                    )
            </div>
        </div>
    </form>

    <div class="row my-4">
        <div class="col-12">
            <div class="row justify-content-around">
                <div class="col-auto btnOutline my-2 mx-auto mx-xl-2 p-0">
                    <button type="button" data-bs-dismiss="modal" aria-label="Close">
                        <h6 class="m-0 px-3"><b>Cerrar</b></h6>
                    </button>
                </div>

                <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                    <div class="controlButton">
                        <button class="btnPrimary px-3" onclick="editarMarca()">
                            <h5 class="m-0"><b>Guardar</b></h5>
                        </button>
                    </div>
                </div>
            </div>
        </div>


    </div>
</section>
<script>
    function editarMarca() {

        var Mydata = $("#EditarMarcaForm").serialize();
        console.log(Mydata);
        $('#editarMarca').modal('hide');
        $('body').removeClass('model-open');
        $('.modal-backdrop').remove();
        $.ajax({
            url: '@Url.Action("UpdatePartialModal")',
            type: 'POST',
            data: Mydata,
            success: function (result) {
                $("#tablaMarcas").html(result);
            }
        });
    }

</script>

Views/MarcasVehiculos/_Update.cshtml
@model GuanajuatoAdminUsuarios.Models.MarcaVehiculoModel
@{
}




<div class="row">
    <div class="col-md-12">
        <form id="EditarMarcaForm" novalidate class="needs-validation">

            @Html.HiddenFor(m=>m.IdMarcaVehiculo)
            @(Html.Kendo().TextBoxFor(t => t.MarcaVehiculo)
                .HtmlAttributes(new { placeholder = "Marca de Vehículo", required = "required", validationmessage = "Enter Category Name" })
                .Label(l => l.Content("Marca de Vehículo"))
                )

        </form>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href='@Url.Action("IndexModal")' class="btn btn-default">Cancelar</a>
                <button class="btn btn-success" onclick="editarMarca()">Guardar</button>
            </div>
        </div>


    </div>
</div>

<script>
    function editarMarca() {

        var Mydata = $("#EditarMarcaForm").serialize();
        console.log(Mydata);
        $('#editarMarca').modal('hide');
        $('body').removeClass('model-open');
        $('.modal-backdrop').remove();
        $.ajax({
            url: '@Url.Action("UpdatePartialModal")',
            type: 'POST',
            data: Mydata,
            success: function (result) {
                $("#tablaMarcas").html(result);
            }
        });
    }

</script>