Controllers/SubmarcasVehiculosController.cs
using GuanajuatoAdminUsuarios.Entity;
using GuanajuatoAdminUsuarios.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Example.WebUI.Controllers
{
    public class SubmarcasVehiculosController : Controller
    {
        DBContextInssoft dbContext = new DBContextInssoft();
        public IActionResult Index()
        {
            //var products = dbContext.Products.ToList();
            var ListSubmarcasModel = GetSubmarcas();

            return View(ListSubmarcasModel);

        }


        #region Modal Action
        public ActionResult IndexModal()
        {
            var ListSubmarcasModel = GetSubmarcas();
            //return View("IndexModal");
            return View("Index", ListSubmarcasModel);
        }

        [HttpPost]
        public ActionResult AgregarSubmarcaParcial()
        {
            SetDDLMarcas();
            return PartialView("_Crear");
        }

        public ActionResult EditarSubmarcaParcial(int IdSubmarca)
        {
            SetDDLMarcas();
            var submarcasModel = GetSubmarcaByID(IdSubmarca);
            return View("_Editar", submarcasModel);
        }

        public ActionResult EliminarSubmarcaParcial(int IdSubmarca)
        {
            SetDDLMarcas();
            var submarcasModel = GetSubmarcaByID(IdSubmarca);
            return View("_Eliminar", submarcasModel);
        }

        public JsonResult Categories_Read()
        {
            var result = new SelectList(dbContext.SubmarcasVehiculos.ToList(), "IdSubmarca", "NombreSubmarca");
            return Json(result);
        }



        [HttpPost]
        public ActionResult CreatePartialModal(SubmarcasVehiculosModel model)
        {
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("NombreSubmarca");
            if (ModelState.IsValid)
            {
                //Crear el producto

                CreateSubmarca(model);
                var ListSubmarcasModel = GetSubmarcas();
                return PartialView("_ListaSubmarcas", ListSubmarcasModel);
            }
            SetDDLMarcas();
            //return View("Create");
            return PartialView("_Crear");
        }

        [HttpPost]
        public ActionResult EditarSubmarca(SubmarcasVehiculosModel model)
        {
            bool switchSubmarcas = Request.Form["submarcasSwitch"].Contains("true");
            model.Estatus = switchSubmarcas ? 1 : 0;
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("NombreSubmarca");
            if (ModelState.IsValid)
            {
                //Crear el producto

                UpdateSubmarca(model);
                var ListSubmarcasModel = GetSubmarcas();
                return PartialView("_ListaSubmarcas", ListSubmarcasModel);
            }
            SetDDLMarcas();
            //return View("Create");
            return PartialView("_Editar");
        }

        [HttpPost]
        public ActionResult EliminarSubmarca(SubmarcasVehiculosModel model)
        {
            var errors = ModelState.Values.Select(s => s.Errors);
            ModelState.Remove("NombreSubmarca");
            if (ModelState.IsValid)
            {
                //Crear el producto

                DeleteSubmarca(model);
                var ListSubmarcasModel = GetSubmarcas();
                return PartialView("_ListaSubmarcas", ListSubmarcasModel);
            }
            SetDDLMarcas();
            //return View("Create");
            return PartialView("_Eliminar");
        }


        public JsonResult GetSubs([DataSourceRequest] DataSourceRequest request)
        {
            var ListSubmarcasModel = GetSubmarcas();

            return Json(ListSubmarcasModel.ToDataSourceResult(request));
        }




        #endregion


        #region Acciones a base de datos

        public void CreateSubmarca(SubmarcasVehiculosModel model)
        {
            SubmarcasVehiculo submarca = new SubmarcasVehiculo();
            submarca.IdSubmarca = model.IdSubmarca;
            submarca.NombreSubmarca = model.NombreSubmarca;
            submarca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            submarca.estatus = 1;
            submarca.FechaActualizacion = DateTime.Now;
            dbContext.SubmarcasVehiculos.Add(submarca);
            dbContext.SaveChanges();
        }

        public void UpdateSubmarca(SubmarcasVehiculosModel model)
        {
            //Sera mas rapido con automapeo de clases
            SubmarcasVehiculo submarca = new SubmarcasVehiculo();
            submarca.IdSubmarca = model.IdSubmarca;
            submarca.NombreSubmarca = model.NombreSubmarca;
            submarca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            submarca.estatus = model.Estatus;
            submarca.FechaActualizacion = DateTime.Now;
            dbContext.Entry(submarca).State = EntityState.Modified;
            dbContext.SaveChanges();

        }

        public void DeleteSubmarca(SubmarcasVehiculosModel model)
        {
            //Sera mas rapido con automapeo de clases
            SubmarcasVehiculo submarca = new SubmarcasVehiculo();
            submarca.IdSubmarca = model.IdSubmarca;
            submarca.NombreSubmarca = model.NombreSubmarca;
            submarca.IdMarcaVehiculo = model.IdMarcaVehiculo;
            submarca.estatus = 0;
            submarca.FechaActualizacion = DateTime.Now;
            dbContext.Entry(submarca).State = EntityState.Modified;
            dbContext.SaveChanges();

        }

        private void SetDDLMarcas()
        {
            ///Espacio en memoria de manera temporal que solo existe en la petición bool, list, string ,clases , selectlist
            ViewBag.Marcas = new SelectList(dbContext.MarcasVehiculos.ToList(), "IdMarcaVehiculo", "MarcaVehiculo");
        }

        [HttpPost]
        public IActionResult MarcasDDL(SubmarcasVehiculo submarcasModel)
        {
            GetSubmarcasWithMarcas();
            var catID = submarcasModel.IdMarcaVehiculo;
            return View();
        }


        public SubmarcasVehiculosModel GetSubmarcaByID(int IdSubmarca)
        {

            var productEnitity = dbContext.SubmarcasVehiculos.Find(IdSubmarca);

            var submarcaModel = (from submarcasVehiculos in dbContext.SubmarcasVehiculos.ToList()
                                 select new SubmarcasVehiculosModel

                                 {
                                     IdSubmarca = submarcasVehiculos.IdSubmarca,
                                     NombreSubmarca = submarcasVehiculos.NombreSubmarca,


                                 }).Where(w => w.IdSubmarca == IdSubmarca).FirstOrDefault();

            return submarcaModel;
        }

        /// <summary>
        /// Linq es una tecnologia de control de datos (excel, txt,EF,sqlclient etc)
        /// para la gestion un mejor control de la info
        /// </summary>
        /// <returns></returns>
        /// 
        public List<SubmarcasVehiculosModel> GetSubmarcasWithMarcas()
        {
            var ListSubmarcasModel = (from SubmarcasVehiculo in dbContext.SubmarcasVehiculos.ToList()
                                      join MarcasVehiculo in dbContext.MarcasVehiculos.ToList()
                                      on SubmarcasVehiculo.IdMarcaVehiculo equals MarcasVehiculo.IdMarcaVehiculo
                                      select new SubmarcasVehiculosModel
                                      {
                                          IdSubmarca = SubmarcasVehiculo.IdSubmarca,
                                          NombreSubmarca = SubmarcasVehiculo.NombreSubmarca,
                                          IdMarcaVehiculo = MarcasVehiculo.IdMarcaVehiculo,


                                      }).ToList();
            return ListSubmarcasModel;
        }
        public List<SubmarcasVehiculosModel> GetSubmarcas()
        {
            var ListSubmarcasModel = (from submarcasVehiculo in dbContext.SubmarcasVehiculos.ToList()
                                      join marcasVehiculos in dbContext.MarcasVehiculos.ToList()
                                      on submarcasVehiculo.IdMarcaVehiculo equals marcasVehiculos.IdMarcaVehiculo
                                      join estatus in dbContext.Estatus.ToList()
                                      on submarcasVehiculo.estatus equals estatus.estatus
                                      where submarcasVehiculo.estatus == 1
                                      select new SubmarcasVehiculosModel

                                      {
                                          IdSubmarca = submarcasVehiculo.IdSubmarca,
                                          NombreSubmarca = submarcasVehiculo.NombreSubmarca,
                                          Estatus = estatus.estatus,
                                          estatusDesc = estatus.estatusDesc,
                                          IdMarcaVehiculo = submarcasVehiculo.IdMarcaVehiculo,
                                          MarcaVehiculo = marcasVehiculos.MarcaVehiculo


                                      }).ToList();
            return ListSubmarcasModel;
        }
        #endregion



    }
}

Views/SubmarcasVehiculos/Create.cshtml
        <div class="modal-content"id="addSubmarcaBody">

            <section class=" bg-white rounded">
                <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                    <div class="col-auto pe-0">
                        <div class="row align-items-center justify-content-center justify-content-md-start">
                            <div class="col-auto pe-0">
                                <i class="icon-addSubMarcar h1 colorPrimary"></i>
                            </div>
                            <div class="col-auto my-3">
                                <h2 class="m-0 h3"><b>Agregar submarca de vehículo</b></h2>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div class="row">
                            <div class="col-auto my-3">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="bg-light py-1"></div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-12 col-lg-6 my-4">
                        <h5 class="px-4"><b>Datos de submarca de vehículo</b></h5>
                        <h6 class="px-4 text-muted">Completa los datos obligatorios para guardar.</h6>
                    </div>
                </div>
                <form class="row px-4 mb-4 align-items-end justify-content-center">
                    <div class="col-12 col-md-6">
                        <div class="controlForm my-3">
                            <label>Marca<b>(obligatorio)</b>:</label>
                            <span>
                                @(Html.Kendo().DropDownList()
                                    .Name("marcaAddSubMarca")
                                    .DataTextField("")
                                    .DataValueField("")
                                    .HtmlAttributes(new { style = "width:100%;" })
                                    .Filter(FilterType.Contains)
                                    .DataSource(source => source
                                    .Read(read => read.Action("GetProducts", "Home"))
                                    )
                                    )
                            </span>
                        </div>
                    </div>
                    <div class="col-12 col-md-6">
                        <div class="controlForm my-3">
                            @(Html.Kendo().TextBox()
                                .Name("nombreAddSubMarca")
                                .Label(l => l.Content("Submarca <b>(obligatorio)</b>:"))
                                .Placeholder("Ingresa una nueva submarca")
                                .HtmlAttributes(new { style = "width: 100%" })
                                )

                        </div>
                    </div>

                </form>
                <div class="row my-4">
                    <div class="col-12 col-md-6 mx-md-auto">
                        <div class="row justify-content-around">
                            <div class="col-auto btnOutline my-2 mx-auto mx-xl-2 p-0">
                                <button type="button" data-bs-dismiss="modal" aria-label="Close">
                                    <h6 class="m-0 px-3"><b>Cerrar</b></h6>
                                </button>
                            </div>
                            <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                                <div class="controlButton">
                                    @(Html.Kendo().Button()
                                        .Name("AddSubMarca")
                                        .HtmlAttributes(new { @class = "btnPrimary px-3" })
                                        .Content("<h5 class=\"m-0\"><b>Guardar</b></h5>"))
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </section>
        </div>
    </div>
</div>

Views/SubmarcasVehiculos/Delete.cshtml
@model GuanajuatoAdminUsuarios.Models.SubmarcasVehiculosModel
@{
    Layout = null;
}


<div class="row">
    <div class="col-md-10">
        <h2>Eliminar Submarca</h2>
    </div>
    <br />
    <div class="col-md-2">
        @Html.ActionLink("Cancelar","Index",null,new{@class="btn btn-info"})
    </div>
</div>
<hr />
<br />

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Delete", "SubmarcasVehiculos"))
        {
            @Html.HiddenFor(m=>m.IdSubmarca)
            ;

            @(Html.Kendo().TextBoxFor(t => t.NombreSubmarca)
                .HtmlAttributes(new
                {
                    placeholder = "Nombre submarca",
                    required = "required",
                    validationmessage = "Enter Category Name",
                    @readonly = "readonly"
                })
                .Label(l => l.Content("Nombre submarca"))
                )
            <br />  <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href='@Url.Action("Index")' class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </div>

        }

    </div>
</div>

Views/SubmarcasVehiculos/Index.cshtml
@model List<GuanajuatoAdminUsuarios.Models.SubmarcasVehiculosModel>
@*RazorCoder*@

    <div class="mainContainer bg-light">

        <section class="mx-md-3 mx-lg-4 mx-xl-5 bg-white boxShadow my-5 rounded">
            <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                <div class="col-12 col-md-6 col-lg-5 col-xl-auto">
                    <div class="row align-items-center justify-content-center justify-content-md-start">
                        <div class="col-auto">
                            <i class="icon-subMarcar h1 colorPrimary"></i>
                        </div>
                        <div class="col-auto my-3">
                            <h2 class="m-0 h3"><b>Catalogo de submarcas de vehículos</b></h2>
                        </div>
                    </div>
                </div>            
                        <div class="col-12 col-md-6 col-lg-7 col-xl-auto">
                            <div class="row">
                                <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                        <button href="#" id="btnNueop" onclick="mostrarModal()">
                            <h6 class="m-0 d-flex align-items-center"><i class="icon-addSubMarcar h5 mb-0 me-2"></i><b>Agregar nueva submarca de vehículo</b></h6>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="bg-light py-1"></div>
                        </div>
                    </div>
                    <div class="row justify-content-between mb-1 titleCustom">
                        <div class="col-12 col-md-auto mt-4 mb-2">
                            <h5 class="px-4"><b>Listado de submarca de vehículo</b></h5>
                            <h6 class="px-4 text-muted">Edita o elimina las submarcas de vehículos.</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mb-4 px-4 rounded gridCustom">                        
            <div id="tablaSubmarcas">
                <partial name="_ListaSubmarcas" model="Model" />
<!--//////////////////////////////////////////////////////////////////////////////////////*******AGREGAR*******//////////////////////////////////////////////////////////////////////-->
    <div class="modal fade modalCustom" id="agregarSubmarca" tabindex="-1" aria-labelledby="addSubMarcaLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" id="agregarSubmarcaBody">

                </div>
            </div>

        </div>
    </div>

 <!--//////////////////////////////////////////////////////////////////////////////////////*******EDITAR*******//////////////////////////////////////////////////////////////////////-->
  <div class="modal fade modalCustom" id="editarSubMarca" tabindex="-1" aria-labelledby="editarSubMarcaLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-body" id="editarSubmarcaBody">

               </div>
           </div>
       </div>
  </div>

 <!--//////////////////////////////////////////////////////////////////////////////////////*******ELIMINAR*******//////////////////////////////////////////////////////////////////////-->
 <div class="modal fade modalCustom" id="eliminarSubMarca" tabindex="-1" aria-labelledby="eliminarSubMarcaLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-body" id="eliminarSubmarcaBody">

               </div>
           </div>
      </div>
 </div>
                                </div>
                            </div>
                        </div>
        </section>

    </div>

<script>
    function mostrarModal() {
        $.ajax({
            url: '@Url.Action("AgregarSubmarcaParcial")',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                $('#agregarSubmarcaBody').html(data);
                $('#agregarSubmarca').modal('show');
            }
        });
    }


</script>

Views/SubmarcasVehiculos/IndexModal.cshtml
@model List<GuanajuatoAdminUsuarios.Models.SubmarcasVehiculosModel>
@*RazorCoder*@

    <div class="mainContainer bg-light">

        <section class="mx-md-3 mx-lg-4 mx-xl-5 bg-white boxShadow my-5 rounded">
            <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                <div class="col-12 col-md-6 col-lg-5 col-xl-auto">
                    <div class="row align-items-center justify-content-center justify-content-md-start">
                        <div class="col-auto">
                            <i class="icon-subMarcar h1 colorPrimary"></i>
                        </div>
                        <div class="col-auto my-3">
                            <h2 class="m-0 h3"><b>Catalogo de submarcas de vehículos</b></h2>
                        </div>
                    </div>
                </div>            
                        <div class="col-12 col-md-6 col-lg-7 col-xl-auto">
                            <div class="row">
                                <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                        <button href="#" id="btnNueop" onclick="mostrarModal()">
                            <h6 class="m-0 d-flex align-items-center"><i class="icon-addSubMarcar h5 mb-0 me-2"></i><b>Agregar nueva submarca de vehículo</b></h6>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="bg-light py-1"></div>
                        </div>
                    </div>
                    <div class="row justify-content-between mb-1 titleCustom">
                        <div class="col-12 col-md-auto mt-4 mb-2">
                            <h5 class="px-4"><b>Listado de submarca de vehículo</b></h5>
                            <h6 class="px-4 text-muted">Edita o elimina las submarcas de vehículos.</h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 mb-4 px-4 rounded gridCustom">                        
            <div id="tablaSubmarcas">
                <partial name="_ListaSubmarcas" model="Model" />
<!--//////////////////////////////////////////////////////////////////////////////////////*******AGREGAR*******//////////////////////////////////////////////////////////////////////-->
    <div class="modal fade modalCustom" id="agregarSubmarca" tabindex="-1" aria-labelledby="addSubMarcaLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" id="agregarSubmarcaBody">

                </div>
            </div>

        </div>
    </div>

 <!--//////////////////////////////////////////////////////////////////////////////////////*******EDITAR*******//////////////////////////////////////////////////////////////////////-->
  <div class="modal fade modalCustom" id="editarSubMarca" tabindex="-1" aria-labelledby="editarSubMarcaLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-body" id="editarSubmarcaBody">

               </div>
           </div>
       </div>
  </div>

 <!--//////////////////////////////////////////////////////////////////////////////////////*******ELIMINAR*******//////////////////////////////////////////////////////////////////////-->
 <div class="modal fade modalCustom" id="eliminarSubMarca" tabindex="-1" aria-labelledby="eliminarSubMarcaLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg boxShadow modal-dialog-centered">
           <div class="modal-content">
               <div class="modal-body" id="eliminarSubmarcaBody">

               </div>
           </div>
      </div>
 </div>
                                </div>
                            </div>
                        </div>
        </section>

    </div>

<script>
    function mostrarModal() {
        $.ajax({
            url: '@Url.Action("AgregarSubmarcaParcial")',
            type: 'POST',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                $('#agregarSubmarcaBody').html(data);
                $('#agregarSubmarca').modal('show');
            }
        });
    }


</script>

Views/SubmarcasVehiculos/Update.cshtml
@model GuanajuatoAdminUsuarios.Models.SubmarcasVehiculosModel
@{
    Layout = null;
}


<div class="row">
    <div class="col-md-10">
        <h2>Modificar Submarca</h2>
    </div>
    <br />
    <div class="col-md-2">
        @Html.ActionLink("Cancelar","Index",null,new{@class="btn btn-info"})
    </div>
</div>
<hr />
<br />

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Update", "SubmarcasVehiculos"))
        {
            @Html.HiddenFor(m=>m.IdSubmarca)
            ;


            @(Html.Kendo().TextBoxFor(t => t.NombreSubmarca)
                .HtmlAttributes(new { placeholder = "Submarca", required = "required", validationmessage = "Introduce nombre de Submarca" })
                .Label(l => l.Content("Submarca"))
                )
            <br />  <br />


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href='@Url.Action("Index")' class="btn btn-default">Cancelar</a>
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </div>

        }

    </div>
</div>

Views/SubmarcasVehiculos/_Crear.cshtml
@model GuanajuatoAdminUsuarios.Models.SubmarcasVehiculosModel
@{
    var marcas = (SelectList)ViewBag.Marcas;

}

                <section class=" bg-white rounded">
                    <div class="row align-items-center justify-content-between px-4 px-md-4 pt-3 pb-2">
                        <div class="col-auto pe-0">
                            <div class="row align-items-center justify-content-center justify-content-md-start">
                                <div class="col-auto pe-0">
                                    <i class="icon-addSubMarcar h1 colorPrimary"></i>
                                </div>
                                <div class="col-auto my-3">
                                    <h2 class="m-0 h3"><b>Agregar submarca de vehículo</b></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-auto">
                            <div class="row">
                                <div class="col-auto my-3">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="bg-light py-1"></div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-12 col-lg-6 my-4">
                            <h5 class="px-4"><b>Datos de submarca de vehículo</b></h5>
                            <h6 class="px-4 text-muted">Completa los datos obligatorios para guardar.</h6>
                        </div>
                    </div>
                    <form id="ProductForm" class="row px-4 mb-4 align-items-end justify-content-center">
                        <div class="col-12 col-md-6">
                            <div class="controlForm my-3">
                                <label>Marca<b>(obligatorio)</b>:</label>
                                <span>
                                  @Html.DropDownListFor(t=>t.IdMarcaVehiculo,marcas)
                                        
                                        
                                        
                                </span>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="controlForm my-3">
                                @(Html.Kendo().TextBoxFor(t=>t.NombreSubmarca)
                                    
                                    .Label(l => l.Content("Submarca <b>(obligatorio)</b>:"))
                                    .Placeholder("Ingresa una nueva submarca")
                                    .HtmlAttributes(new { style = "width: 100%" })
                                    )

                            </div>
                        </div>

                    </form>
                    <div class="row my-4">
                        <div class="col-12 col-md-6 mx-md-auto">
                            <div class="row justify-content-around">
                                <div class="col-auto btnOutline my-2 mx-auto mx-xl-2 p-0">
                                    <button type="button" data-bs-dismiss="modal" aria-label="Close">
                                        <h6 class="m-0 px-3"><b>Cerrar</b></h6>
                                    </button>
                                </div>
                                <div class="col-auto btnOutline btnOutlinePrimary my-2 mx-auto mx-xl-2 p-0">
                                    <div class="controlButton">
                                    <button class="btnPrimary px-3" onclick="submitProduct()">
                                        <h5 class="m-0"><b>Guardar</b></h5>
                                     </button> 
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </section>


<script>
    function submitProduct() {

        var Mydata = $("#ProductForm").serialize();
        console.log(Mydata);
        $('#addSubMarca').modal('hide');
        $('body').removeClass('model-open');
        $('.modal-backdrop').remove();
        $.ajax({
            url: '@Url.Action("CreatePartialModal")',
            type: 'POST',
            data: Mydata,
            success: function (result) {
                $("#tablaSubmarcas").html(result);
            }
        });
    }

</script>